### ISSUE TITLE
Dark and light theme with switch

### ISSUE THREAD

**Issue by boopathikumar018** [pajaydev/ebay-node-api#100]
Hi

Dark and light theme with switch using [docsify-darklight-theme](https://docsify-darklight-theme.boopathikumar.me/#/) for you docsify documentation.

**Comment by pajaydev** [comment]
@boopathikumar018  That's really cool.
Feel free to contribute if you want, this is the branch we use for documentation

https://github.com/pajaydev/ebay-node-api/tree/gh-pages

**Comment by boopathikumar018** [comment]
Hi @pajaydev,

Please find the [PR](https://github.com/pajaydev/ebay-node-api/pull/101).

**Comment by pajaydev** [comment]
Looks good. Thanks 👍
