### ISSUE TITLE
Can't resolve 'fs'

### ISSUE THREAD

**Issue by cheersdigital** [pajaydev/ebay-node-api#102]
Hi,

I receive the following issue when I require the ebay-node-api package. I'm using Nuxt.js framework. 

Module not found: Error: Can't resolve 'fs'

I tried to install 'fs' at project level but that doesn't help. 

Cheers

**Comment by pajaydev** [comment]
@cheersdigital hey Tim, did this issue got resolved ??

**Comment by cheersdigital** [comment]
Hi Ajay. Yeah I found a solution and marked it resolved. 

Is there any way around CORS with this package? I can use a proxy but need to change the base auto to be something different. 

Cheers

Tim

**Comment by pajaydev** [comment]
@cheersdigital  Hey you can create an proxy in your server like this. am calling on click of button on server-side.

https://gist.github.com/pajaydev/b10b4d29bae85b441954d298a9e0d2c3
