### ISSUE TITLE
findItemsByCategory is not supporting filters

### ISSUE THREAD

**Issue by pajaydev** [pajaydev/ebay-node-api#103]
@doverradio reported

Hi, I tried using the filters in FindItemsByCategory in this way

ebay.findItemsByCategory({
    categoryID: 10181,

}).then((data) => {
    // console.log(data);
    console.log(data[0].errorMessage[0].error[0].message[0]);
}, (error) => {
    console.log(error);
});
but got error Invalid category ID.

How can I pass in filters on this call?

If I deviate from your example it constantly fails but I need to specify show sold only and price range.

After I checked your source code, perhaps you could replace the current function with this to the function:

const findItemsByCategory = function (options) {
    let categoryID = options.categoryID;
    if (!options.categoryID) throw new Error('INVALID_REQUEST_PARMS --> Category ID is null or invalid');
    this.options.name = categoryID;
    this.options.operationName = FIND_ITEMS_BY_CATEGORY;
    this.options.param = 'categoryId';
    this.options.additionalParam = constructAdditionalParams(options);
    const url = urlObject.buildSearchUrl(this.options);
    return getRequest(url).then((data) => {
        return JSON.parse(data).findItemsByCategoryResponse;
    }, console.error // eslint-disable-line no-console
    );
};
After applying the above, my code now works using that.

**Comment by doverradio** [comment]
Sorry, there is yet one more parameter I am trying to get in, show only BuyItNow or FixedPrice.  Is there a way to do that currently?  I tried passing in different parameters but fails and always includes Auction.

**Comment by pajaydev** [comment]
@doverradio You can filter the buy it now items like this


```javascript
ebay.findItemsAdvanced({
    entriesPerPage: 2,
    keywords: 'ipad',
    ExpeditedShippingType: 'OneDayShipping',
    ListingType: 'AuctionWithBIN'
}).then((data) => {
    console.log(data);
}, (error) => {
    console.log(error);
});
```

**Comment by doverradio** [comment]
Tho your example worked, I was unable to figure out how to pass in the category properly.  When I do this:
```
ebay.findItemsAdvanced({
  entriesPerPage: 2,
  // keywords: 'ipad',
  categoryId: '45510',
  // SoldItemsOnly: true,
  // ExpeditedShippingType: 'OneDayShipping',
  ListingType: 'AuctionWithBIN'
})
```

 it gives no results.  I just want to get all the Sold Only, Buy It Now, Free Shipping, and US Only items for each category on Ebay.  What is the correct call to make for these conditions?

**Comment by pajaydev** [comment]
@doverradio  It's working for me, which version are you using ?.

**Comment by pajaydev** [comment]
@doverradio  Added this in version 2.8.7. Kindly install this version and try

```
npm install ebay-node-api@2.8.7
```
