### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by mako10110** [pajaydev/ebay-node-api#110]
ebay.getItemStatus(['153265274986', '153265274986']).then((data) => {
        console.log(data);
    }, (error) => {
        console.log(error);
    });

this method triggers SyntaxError: Unexpected end of JSON input

**Comment by pajaydev** [comment]
@mako10110  Are you using like this 

```javascript
const Ebay = require('ebay-node-api');

let ebay = new Ebay({
    clientID: 'XXXXXX',
});

ebay.getItemStatus(['153265274986', '153265274986']).then((data) => {
    console.log(data);
    }, (error) => {
    console.log(error);
    });

```

It works fine to me.

**Comment by pajaydev** [comment]
@mako10110  Closing this, kindly re-open the issue if you have any concerns.

**Comment by emporioreale** [comment]
I am getting that error
`Uncaught SyntaxError SyntaxError: Unexpected end of JSON input
`
