### ISSUE TITLE
Cannot Install Package

### ISSUE THREAD

**Issue by aacase** [pajaydev/ebay-node-api#113]
`error Received malformed response from registry for "oauth-ebay". The registry may be down.`

I checked, and that package is 404ing from the npm registry.

**Comment by yaroslaviy** [comment]
Same issue, ```oauth-ebay``` has been removed

**Comment by pajaydev** [comment]
@aacase  @yaroslaviy  Sorry for the inconvinience, we had to remove the oauth-ebay for security reasons. I have published a new package, kindly try now

```
yarn add ebay-node-api
or 
npm install ebay-node-api
```

**Comment by pajaydev** [comment]
https://github.com/pajaydev/ebay-node-api/pull/114

**Comment by pajaydev** [comment]
Closing this
