### ISSUE TITLE
Npm install is failing 

### ISSUE THREAD

**Issue by adibenmati** [pajaydev/ebay-node-api#115]
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/oauth-ebay/-/oauth-ebay-1.3.2.tgz
npm ERR! 404 
npm ERR! 404  'oauth-ebay@1.3.2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'ecoprice-backend'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by pajaydev** [comment]
@adibenmati  Kindly install the library again, you wont face this issue 

```
yarn add ebay-node-api 
```
or 
```
npm install ebay-node-api 
```

**Comment by pajaydev** [comment]
Closing this. Kindly let me know if you are facing this issue
