### ISSUE TITLE
Module 'ebay-node-api', not found

### ISSUE THREAD

**Issue by hendo10** [pajaydev/ebay-node-api#124]
I get the following error when using 'const eBay = require('ebay-node-api')'

Error message:  'Could not find a declaration file for module 'ebay-node-api'. '/..node_modules/ebay-node-api/src/index.js' implicitly has an 'any' type.'

Can somebody advise?

**Comment by pajaydev** [comment]
@hendo10  Kindly delete the node modules folder and try to install it again.

```
yarn add ebay-node-api
or 
npm install ebay-node-api
```

**Comment by hendo10** [comment]
This work.  Thank you @pajaydev
