### ISSUE TITLE
findCompletedItems deprecation

### ISSUE THREAD

**Issue by zslabs** [pajaydev/ebay-node-api#125]
👋 @pajaydev 

Due to the recent announcement that the `findCompletedItems` endpoint will be deprecated without the Market Insights API, I wanted to see if you had any thoughts on if adding support for `itemFilters` in `findItemsAdvanced` https://developer.ebay.com/DevZone/finding/CallRef/findItemsAdvanced.html would be possible, so we could pass through the `SellingState` https://developer.ebay.com/devzone/finding/callref/findItemsAdvanced.html#Response.searchResult.item.sellingStatus.sellingState

**Comment by pajaydev** [comment]
@zslabs  Thanks for reporting this. yes, sure we can add support in itemsFilters. Free feel to do this change if you want to take this up or I will do.

**Comment by zslabs** [comment]
Thanks for the quick response! I noticed that the `constructAdditionalParams` function you have should technically take care of this, but what I'm a bit confused about is how we'd have both `sellingStatus` and `sellingState` as it's a sub-property of this item filter. If you do end up having a few to look at this, I'd really appreciate it. Thanks as always!

**Comment by zslabs** [comment]
Hm, even though I'm seeing `SoldItemsOnly` on https://developer.ebay.com/DevZone/finding/CallRef/types/ItemFilterType.html (as I thought `sellingState` might be available), it is marked as "future" and I'm not getting any results using that in the API playground.

If you have any thoughts, we might need to get a bit creative here unfortunately :(

Some more discussion https://forums.developer.ebay.com/questions/37466/findcompleteditems-dropped-from-finding-api.html

**Comment by pajaydev** [comment]
@zslabs Thanks for looking into this. Let me take a look and get back to you.

**Comment by zslabs** [comment]
Until eBay either adds the endpoint back (unlikely) or enables the sold filter on the advanced search, it doesn't look like there's an option here.
