### ISSUE TITLE
getDeals doesn't work anymore (error 404)

### ISSUE THREAD

**Issue by paridao** [pajaydev/ebay-node-api#126]
Seems Ebay removed the feed.

Steps to reproduce (the same as the relative example):

`let ebay = new Ebay({
    clientID: clientId,
    clientSecret: clientSecret,
    body: {
        grant_type: 'client_credentials',
        scope: 'https://api.ebay.com/oauth/api_scope'

    }
});

    // get top ten deals in US.
    ebay.getDeals().then((data) => {
        console.log(data);
    }).catch(err =>{
       // ERROR HERE
        console.error(err);
    });

    // get deals for specific country code and category
    ebay.getDeals({
        limit: 50, // no of deals per request
        countryCode:'ebay-de', 
        eBayCatId: '1234' // deal for specific category id
    }).then((data) => {
        console.log(data);
    }).catch(err =>{
        // ERROR HERE
        console.error(err);
    });`

**Comment by pajaydev** [comment]
@paridao  Thanks for raising this. Let me announce it as deprecated in the next version.

**Comment by pajaydev** [comment]
@paridao  included temporary documentation. Will remove it completely in the major version.

**Comment by pajaydev** [comment]
@paridao  included temporary documentation. Will remove it completely in the major version.
