### ISSUE TITLE
Auth flow equivalent to getUserDetails?

### ISSUE THREAD

**Issue by rambonette** [pajaydev/ebay-node-api#141]
### Issue or Enhancement

* [ ] Issue
* [x ] Enhancement / Improvement

### Expected Behavior

Is there a way to get shop/user details (like `getUserDetails`) using the auth flow?

**Comment by pajaydev** [comment]
@rambonette  This library is already supporting `getUserDetails`. You can check the example here
https://github.com/pajaydev/ebay-node-api/blob/642a273df4a474cc6112befa6992ee711d231139/demo/shopping.js#L19

**Comment by rambonette** [comment]
Any news? Is this library using the OAuth flow?

**Comment by pajaydev** [comment]
@rambonette  We don't need oauth flow to get the user details. Above method should work. To look more around oauth flow, kindly check this library [ebay-oauth-nodejs-client](https://github.com/pajaydev/ebay-oauth-nodejs-client). You can wrap this around it.

**Comment by rambonette** [comment]
That's exactly what I've done! Thank you :)
