### ISSUE TITLE
plan to update npm package? 

### ISSUE THREAD

**Issue by rambonette** [pajaydev/ebay-node-api#153]
### Issue or Enhancement

* [ ] Issue
* [ x] Enhancement / Improvement

### Steps to reproduce

Hi @pajaydev :) ! Currently is not possible to search by epid code using searchItems() with 'ebay-node-api' npm package, but code in this repo allows it. Are you planning to update the npm package? 

### Expected Behavior

Normal expectation is to be able to search by epid using the npm package

### Actual Behavior

find { offset: 0, epid: '21023325241' }
Error: Error --> Keyword or category id is required in query param
    at Ebay.searchItems (/root/node_modules/ebay-node-api/src/buy-api.js:52:88)

**Comment by pajaydev** [comment]
Thanks for bringing this up. Published a new version `ebay-node-api@2.9.0`

**Comment by rambonette** [comment]
Thank you! Have a nice one ;)

**Comment by rambonette** [comment]
Hi @pajaydev ! Hope you're doing well :)

Seems like, although npm version has been bumped, `searchItems` function in `buy-api.js` is still the old one! As a matter of fact, I still get the old error log:

`UnhandledPromiseRejectionWarning: Error: Error --> Keyword orcategory id is required in query param`

Should be this instead (according to latest commit):

`Error --> Kindly provide the valid Keyword, category id, epid or gtin in query param`

Let me know! Take care ;)

**Comment by rambonette** [comment]
nm turns out i was using and old version :')
