### ISSUE TITLE
findCompletedItems support

### ISSUE THREAD

**Issue by zslabs** [pajaydev/ebay-node-api#45]
👋 @pajaydev 

Thanks for creating this! I was wondering if you had any thoughts on supporting the [findCompletedItems](https://developer.ebay.com/devzone/finding/callref/findCompletedItems.html) method; as I'm attempting to create an interface that users can use to not only see current listings, but also completed listings to gauge market-value.

In addition (I can also create another ticket on this if needed) is there an example of implementing the sort order param?

Thanks again and have a great day!

**Comment by pajaydev** [comment]
@zslabs  Thank u so much for raising this. I can add the support for `findCompletedItems`, I will prioritize this. I will let you know once am done.

**Comment by zslabs** [comment]
Thank you very much for the quick response and for looking into this!

**Comment by pajaydev** [comment]
@zslabs  published in `ebay-node-api@2.6.0`

**Comment by zslabs** [comment]
Thanks for doing this!

**Comment by ethanlaj** [comment]
According to ebay: This call is deprecated as of October 15, 2020, and access is restricted. Is there support for the [Marketplace Insights API](https://developer.ebay.com/api-docs/buy/marketplace-insights/overview.html)?
