### ISSUE TITLE
Some way to add custom headers

### ISSUE THREAD

**Issue by daveybrown** [pajaydev/ebay-node-api#49]
As far as I can tell, if I want to use ebay from a non US country. I need to send a custom header with each request. Something like...

`'X-EBAY-C-MARKETPLACE-ID': 'EBAY_GB',`

Is there a nice way to integrate this into the project?

**Comment by pajaydev** [comment]
@daveybrown  Right now custom headers are not supported in this repo. I would love to include this feature. If you are interested, you can work on this or I can take this up.

**Comment by daveybrown** [comment]
Hi @pajaydev , right now, I'm working on a project and I don't have much spare time. When the project is launched I plan to contribute to the packages I've used. I'll hopefully be in contact then. Thanks bro :)

**Comment by pajaydev** [comment]
@daveybrown  You can use custom headers using this version `ebay-node-api@2.7.0`

**Comment by daveybrown** [comment]
Awesome!
