### ISSUE TITLE
Can I Search By Keyword and Category?

### ISSUE THREAD

**Issue by pythoncreate** [pajaydev/ebay-node-api#58]
Sorry if this is a dumb question, but I'm having a hard time figuring out how to query the API on both keyword and category ID.   I see that ability in find advanced in ebay api, but i don't see that ability here.  Am I wrong?  Thanks

**Comment by pajaydev** [comment]
@pythoncreate  Let me check

**Comment by pajaydev** [comment]
@pythoncreate  you can use something like this 

``` javascript
ebay.getAccessToken()
    .then((data) => {
        ebay.searchItems({
            keyword: 'phone',
            categoryId: 220
        }).then((data) => {
            console.log(data);
            // Data is in format of JSON
            // To check the format of Data, Go to this url (https://developer.ebay.com/api-docs/buy/browse/resources/item_summary/methods/search#w4-w1-w4-SearchforItemsbyKeyword-0)
        })
    });
```

**Comment by pajaydev** [comment]
@pythoncreate  Closing this issue. Kindly create new one if the solution not working.

**Comment by wittyapps** [comment]
can we get this to work with "findItemsByKeywords" method as well?
