### ISSUE TITLE
Add other params

### ISSUE THREAD

**Issue by kkis** [pajaydev/ebay-node-api#59]
Hello Ajaykumar,

Maybe you can add an option to add other params to the buildSearchUrl() method?

something like:    

```javascript
buildSearchUrl(){
...  
if (options.params) {
        Object.keys(options.params).map(key => {
          return baseUrl += '&' + key + '=' + options.params[key];
        })
      }
...
}
```

Or is it already included and i miss it?

Best
Kevin

**Comment by pajaydev** [comment]
Hey Kevin, Thanks for creating this issue. 
I thought I have covered maximum of the params. Feel free to add if you want this to be added.

Few params have mismatch like api has param `paginationInput.pageNumber` but I accept `pageNumber` so in that case the above function won't work.

I am also thinking to revisit this logic, Free feel to play around with it and let me know if you find any better solution.

Thanks.

**Comment by pajaydev** [comment]
@kkis  am closing this issue. Kindly create one if you still have any issue.

Thanks!.
