### ISSUE TITLE
How can you use searchByImage with ebay-node-api?

### ISSUE THREAD

**Issue by doverradio** [pajaydev/ebay-node-api#60]
Hello, Ebay is [giving API access on searchbyimage](https://developer.ebay.com/api-docs/buy/browse/resources/search_by_image/methods/searchByImage). Can this be used with your library? I want to search ebay for items with only image.

**Comment by pajaydev** [comment]
@doverradio  Right now it's not supported. I will try to integrate it. If you are willing to contribute, you can take up this one.

**Comment by pajaydev** [comment]
@doverradio  I have published the changes. You can install ```npm i ebay-node-api``` to get the latest changes.

Kindly check here for reference to use the api
https://github.com/pajaydev/ebay-node-api/blob/master/demo/searchApi.js#L92

Closing this, kindly create a new issue if you have any concerns
