### ISSUE TITLE
Unable to search by UPC code when using findItemsByProduct

### ISSUE THREAD

**Issue by doverradio** [pajaydev/ebay-node-api#62]
Hello, 

I find that I am unable to retrieve products when using the findItemsByProduct call and wonder if perhaps I am using it wrong.

Please find my code below:
```
ebay.getAccessToken().then((data) => {
    ebay.findItemsByProduct({
    productId: 098811586707
    }).then((data) => {
        console.log('searchResult: ', data[0]['searchResult']);
        console.log('Full Object: ', data);
    }, (error) => {
        console.log(error);
    });
});
```

I am using UPC code 098811586707 for testing.  It is clearly associated with [this item on ebay](https://www.ebay.com/itm/RUGGABLE-Washable-Stain-Resistant-Pet-Area-Rug-Noor-Sapphire-Sapphire-8-x-10/401959598369) (scroll down until you find item specifics and 098811586707 is shown there).

Is there something wrong with the way I wrote the code that I get no result after making the call, despite the item showing UPC right on the page?

**Comment by pajaydev** [comment]
@doverradio Thanks for reporting. I tried couple of methods, it didn't work.
I have raised this issue in ebay forum, let's wait for solution.
https://forums.developer.ebay.com/questions/33499/i-need-to-search-for-a-product-with-upc-type.html
Until that you can use `searchProductByKeyword` if you have keyword combination.

**Comment by doverradio** [comment]
Yes, I was able to successfully query for UPC codes via searchProducByKeyword.  Thanks so much!

As an aside, do you know how I can filter the results?  I want to create separate results for sold, unsold.

Can this be accomplished?

**Comment by pajaydev** [comment]
@doverradio  How you were able to query successfully ?. Is it possible to share the query ?.
meanwhile, I will look into the filter part.

**Comment by doverradio** [comment]
Yes sure, here is my code (works):

```
const Ebay = require('ebay-node-api');

var myArgs = process.argv.slice(2);

query = myArgs[0]

let ebay = new Ebay({
    clientID: XXXXX,
    clientSecret: XXXXX,
    body: {
        grant_type: 'client_credentials',
    //you may need to define the oauth scope
    scope: 'https://api.ebay.com/oauth/api_scope'
    }
});
ebay.getAccessToken().then((data) => {
    //This call searches for items on eBay by a keyword and UPC query
    ebay.findItemsByKeywords(query).then((data) => {
        var raw_item_array = data[0].searchResult[0].item;
        console.log('Here is the raw_item_array: ', raw_item_array);
        var raw_item_array_length = raw_item_array.length;
        console.log('Here is the raw_item_array length: ', raw_item_array_length);
    }, (error) => {
        console.log(error);
    });

}, (error) => {
    console.log(error);
});

```

**Comment by pajaydev** [comment]
@doverradio  Thanks for sharing the code. I have included support for aspect_filter in `findItemsByKeyword` method. Kindly get the newer version `yarn install ebay-node-api@2.7.4`.
You can use like this for sold and unsold 

```javascript
ebay.findItemsByKeywords({
    keywords: 'iphone',
    sortOrder: 'PricePlusShippingLowest', //https://developer.ebay.com/devzone/finding/callref/extra/fndcmpltditms.rqst.srtordr.html
    Condition: 3000,
    SoldItemsOnly: false // this will give you unsold items. (true will give you sold items).
}).then((data) => {
    console.log(data);
}, (error) => {
    console.log(error);
});
```

Kindly let me know if you are facing any issues.

**Comment by pajaydev** [comment]
@doverradio  Closing this. Kindly create a new one if you face any other issue.
