### ISSUE TITLE
Problem with aspect_filter at .searchItems

### ISSUE THREAD

**Issue by nickpap2** [pajaydev/ebay-node-api#63]
Hello. Really nice work I like it very much.
I have a problem , although I use the right code it just does not recognizes aspect_filter and it returns phones in general ( I put phones as an example). Am I doing something wrong?
code:

const APIData = JSON.parse(await ebay.searchItems({
        keyword: 'phones',
        limit: '30',
        sort: '',
        offset: 0,
        filter: `price:[${Filters.minPrice}..${Filters.maxPrice}],priceCurrency:EUR`,
        fieldgroups: 'ASPECT_REFINEMENTS,MATCHING_ITEMS',
        aspect_filter: "categoryId:9355,Brand:{LG}"
       
    }));

*the code runs well and it returns phones ,but not LG ,it is like aspect_filter does not exist.

**Comment by nickpap2** [comment]
Turns out there wasn't any code for aspect_filter thats why it didn't work.I wrote the code and made a pull request .Have a nice day.

**Comment by pajaydev** [comment]
@nickpap2  Published a new version with your changes `ebay-node-api@2.7.4`. Thanks.
