### ISSUE TITLE
Request - findItemsAdvanced

### ISSUE THREAD

**Issue by patchcad** [pajaydev/ebay-node-api#67]
Hello,

Would it be possible to add the **findItemsAdvanced** search function? There doesn't seem to be any other way to filter by categoryId without it.

Thank you very much!

Adam

**Comment by pajaydev** [comment]
@patchcad  Sure. I will add, free feel if you want to contribute this.

**Comment by patchcad** [comment]
Thank you very very much!!!

**Comment by pajaydev** [comment]
@patchcad  You can install the latest version to get this `npm install ebay-node-api@2.7.6`

**Comment by patchcad** [comment]
Thank you so very very much!!! It's working perfectly!!!

Merry Christmas and Happy Holidays!
