### ISSUE TITLE
Get seller items

### ISSUE THREAD

**Issue by zslabs** [pajaydev/ebay-node-api#70]
I was hoping `searchItems` would just allow me to use the `filter` param to pass through just a seller, but a keyword is required. Any thoughts on a way around this, or is there another endpoint that could be utilized to achieve listing a seller's items? Basically - the results from a page like https://www.ebay.com/sch/zroddick77/m.html?_nkw=&_armrs=1&_ipg=&_from=

**Comment by zslabs** [comment]
Found it! You can use the following (for anyone else that needs it):

```
findItemsAdvanced({
  LocatedIn: 'WorldWide',
  Seller: 'USERNAME_HERE',
})
```

**Comment by pajaydev** [comment]
@zslabs cool thanks 👍

**Comment by insanity54** [comment]
I was looking for this also. I found that I can do the following.

```
await ebay.searchItems({
  keyword: 'card',
  categoryId: '1345',
  filter: 'sellers:{sakurablossomtradingpost}', // <-- relevant filter
});
```

ebay doc: https://developer.ebay.com/api-docs/buy/static/ref-buy-browse-filters.html#sellers
