### ISSUE TITLE
findItemsByKeywords - when keywords value passed in as object, spaces seem erroneously removed

### ISSUE THREAD

**Issue by abbadata** [pajaydev/ebay-node-api#76]
The following two calls to findItemsByKeywords should return the same results:

ebay.findItemsByKeywords({ keywords: "ralph lauren polo" }).then(
  data => {
    console.log("DATA: ", data);
    console.log(" searchResult: ", data[0].searchResult);
  },
  error => {
    console.log(error);
  }
);

ebay.findItemsByKeywords("ralph lauren polo").then(
  data => {
    console.log("DATA: ", data);
    console.log(" searchResult: ", data[0].searchResult);
  },
  error => {
    console.log(error);
  }
);

However, the first call doesn't return any results since the keywords is getting set to "ralphlaurenpolo".

**Comment by pajaydev** [comment]
Closing as this is fixed.
