### ISSUE TITLE
Add wrappers for GetSingleItem and GetMultipleItems of the shopping api

### ISSUE THREAD

**Issue by IIdmscII** [pajaydev/ebay-node-api#83]
Hey thanks for the great work!
If you have time I could use wrapper functions for the api calls GetSingleItem and GetMultipleItems from the shopping api. Thx!

See: https://developer.ebay.com/devzone/shopping/docs/CallRef/GetSingleItem.html
and https://developer.ebay.com/devzone/shopping/docs/CallRef/GetMultipleItems.html

**Comment by pajaydev** [comment]
@IIdmscII  Thanks for using this library. I will keep it in my list todo.

**Comment by pajaydev** [comment]
@IIdmscII  Its fixed in this version. Kindly use `ebay-node-api@2.8.3`

**Comment by pajaydev** [comment]
Closing this. Kindly create a new issue if you are facing any issue.
