### ISSUE TITLE
constructAdditionalParams seems out of place

### ISSUE THREAD

**Issue by insanity54** [pajaydev/ebay-node-api#87]
I think the [constructAdditionalParams method](https://github.com/pajaydev/ebay-node-api/blob/c36e6b3d566cde7d8aa4dcdf041c3d8a2b7f92ab/src/findingApi.js#L115) Is useful for more modules than just findingApi. I think it makes sense to put that method in `src/common-utils/index.js` instead of `src/findingApi.js`

**Comment by pajaydev** [comment]
@insanity54  Sounds good. if you like to contribute, you can create a PR with this change. Thanks

**Comment by pajaydev** [comment]
@insanity54 Fixed it in #94
