### ISSUE TITLE
2.8.2 > 2.8.3 Lost MyWorldLargeImage

### ISSUE THREAD

**Issue by zslabs** [pajaydev/ebay-node-api#88]
👋 When upgrading to `2.8.3` `User.MyWorldLargeImage` that is normally attached to `getUserDetails` is not being returned anymore. cc @pajaydev

**Comment by pajaydev** [comment]
@zslabs  My bad. I realized it just now. Thanks for reporting, let me fix it and republish it.

**Comment by pajaydev** [comment]
@zslabs  I have fixed it in `ebay-node-api@2.8.4` Kindly test it. Thanks 👍

**Comment by zslabs** [comment]
That did it, thanks!

**Comment by pajaydev** [comment]
Cool 👍
