### ISSUE TITLE
Can you find items by seller?

### ISSUE THREAD

**Issue by doverradio** [pajaydev/ebay-node-api#92]
Hello, I want to get all the items for a specific seller on ebay.  I checked the ebay api and there is a call findItemsIneBayStores.  However, I tried using with your library so far it didn't work.  Can I find items by a specific seller with your library?

**Comment by pajaydev** [comment]
@doverradio  I think the best api you can go with is `findItemsIneBayStores`, will integerate this library with `findItemsIneBayStores`. Thanks for raising this issue.

**Comment by doverradio** [comment]
Yes. Are you planning to update the library with this feature?

**Comment by pajaydev** [comment]
@doverradio  yes, I will try to publish it tonight.

**Comment by doverradio** [comment]
Oh man that is totally great news!

If you added the ability to sell items, that would be the greatest.
(Things to consider)

**Comment by TotallyNotChase** [comment]
@doverradio yes the selling API is in the works

**Comment by pajaydev** [comment]
@doverradio  I can see that there is an existing API that supports to search based on the seller name. Kindly check with the below API. 

```javascript
let ebay = new Ebay({
    clientID: clientId,
});

ebay.findItemsAdvanced({
    Seller: 'batterygallery'
}).then((data) => {
    console.log(data);
}, (error) => {
    console.log(error);
});
```

**Comment by doverradio** [comment]
Hmm, I tried to use findItemsAdvanced but got error:

TypeError: ebay.findItemsAdvanced is not a function

How were you able to use this call?

**Comment by pajaydev** [comment]
@doverradio  which version are you using ?. You can see the reference here https://github.com/pajaydev/ebay-node-api/blob/f3bee06a072f8b56e0be13362374fb2afe0dbd0e/demo/findingApi.js#L62

**Comment by pajaydev** [comment]
@doverradio  I have integerated with `findItemsIneBayStores`. Kindly install the latest version
```
npm install ebay-node-api@2.8.5
```


you can use this method https://github.com/pajaydev/ebay-node-api/blob/master/demo/finding.js#L81

**Comment by pajaydev** [comment]
Closing this issue, kindly create issue if you face any other issues.
