### ISSUE TITLE
Buy Now, US Location Only, Free Shipping, Sort least to greatest

### ISSUE THREAD

**Issue by doverradio** [pajaydev/ebay-node-api#95]
Hello, 

Thank you so much for adding the ability to search by seller.  

1. How do I search for a seller and specify Buy Now, US Location Only, Free Shipping, Sort least to greatest from those results?

2. How do I request these things for when making general search calls not for a specific seller?

**Comment by pajaydev** [comment]
@doverradio  you can search using the browse api with following filters. You can specify the seller name also.
Kindly check this one 
https://developer.ebay.com/api-docs/buy/browse/resources/item_summary/methods/search#h2-input

**Comment by doverradio** [comment]
Hi, I tried using the filters in FindItemsByCategory in this way
```
ebay.findItemsByCategory({
    categoryId: 10181,

}).then((data) => {
    // console.log(data);
    console.log(data[0].errorMessage[0].error[0].message[0]);
}, (error) => {
    console.log(error);
});
```
but got `error Invalid category ID`.

How can I pass in filters on this call?

If I deviate from your example it constantly fails but I need to specify show sold only and price range.

**Comment by pajaydev** [comment]
@doverradio  Thanks for reporting, it was not supporting filtering. Let me make this change quickly.

**Comment by pajaydev** [comment]
Let me create a new issue to keep it separate from this thread.

**Comment by pajaydev** [comment]
@doverradio  you can use this directly like below to get the sold  items

```javascript
ebay.findCompletedItems({
    keywords: 'Garmin nuvi 1300 Automotive GPS Receiver',
    categoryId: '156955',
    sortOrder: 'PricePlusShippingLowest', //https://developer.ebay.com/devzone/finding/callref/extra/fndcmpltditms.rqst.srtordr.html
    Condition: 3000,
    SoldItemsOnly: true,
    entriesPerPage: 2,
}).then((data) => {
    console.log(data);
}, (error) => {
    console.log(error);
});
```

Kindly let me know did i get ur question correct.

**Comment by pajaydev** [comment]
@doverradio Closing this issue, kindly re-open if u r facing this issue
