### ISSUE TITLE
Issue with two "encodeURIComponent" instead of one

### ISSUE THREAD

**Issue by KirianCaumes** [pajaydev/ebay-node-api#96]
Hi,
Just noticed an issue in the last version ("2.8.5") with the method "findItemsByKeywords".
You are calling two times "encodeURIComponent" on the keywords variable :

```js
//findingApi.js l.18
//...
options.keywords = encodeURIComponent(options.keywords);
//...
```

then

```js
//common-utils/index.js l.22
//...
else if (key === 'keywords' || key === 'categoryId' || key === 'productId' || key === 'sortOrder' || key === 'storeName') {
    const encodeParam = encodeURIComponent(options[key]);
    params = `${params}${key}=${encodeParam}&`;
}
//...
```

So keywords like "foo bar" would look like "foo%2520bar" instead of "foo%20bar", resulting in a wrong search against Ebay's API.

Noticed that this issue might be present in other piece of codes, but I haven't checked it.

Hope this will help 😉

**Comment by pajaydev** [comment]
@KirianCaumes  Thanks for pointing this out. I appreciate it 😄 .  Will fix it and release a new version.

**Comment by pajaydev** [comment]
@KirianCaumes  I have fixed it. Kindly use this version 
```npm install ebay-node-api@2.8.6```

**Comment by KirianCaumes** [comment]
No problem 😁
It works fine now, thanks !
